<?xml version = "1.0" encoding = "utf-8"?>
<!DOCTYPE curso [ <!-- definimos el Elemento raiz -->
    <!ELEMENT curso (alumno, alumno)> <!-- curso es un elemnto y contiene dos alumnos -->
        <!ATTLIST curso asignatura CDATA ""> <!-- curso tiene un atributo asignatura que tiene caracter data -->
    <!ELEMENT curso (nombre, calificacion, calificacion, calificacion)> <!-- el elemento aluno tiene nombre, calificacion, calificacion y calificacion -->
        <!ATTLIST alumno id CDATA "0000"> <!-- alumno tiene un atributo id que tiene un caracter data y tiene 0000 por defecto -->
    <!ELEMENT nombre (#PCDATA)> <!-- #PCDATA =  -->
    <!ELEMENT calificacion (#PCDATA)>
    <!ATTLIST calificacion examen CDATA "0">
]>
<curso asignatura = "programacion"<
    <alumno id = "001">
        <nombre> Ana </nombre>
        <calificacion examen = "1"> 10 </calificacion>
        <calificacion examen = "2"> 9.8 </calificacion>
        <calificacion examen = "3"> 10 </calificacion>
    </alumno>
    <alumno id = "021">
        <nombre> Ana </nombre>
        <calificacion examen = "1"> 9 </calificacion>
        <calificacion examen = "2"> 10 </calificacion>
        <calificacion examen = "3"> 8 </calificacion>
    </alumno>
</curso>



<!--

EMPTY:
<!DOCTYPE persona [
<!ELEMENT persona (nombre, mayor_de_edad, ciudad)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT mayor_de_edad EMPTY>
<!ELEMENT ciudad (#PCDATA)>
]>

<persona>
   <nombre>Elsa</nombre>
   <mayor_de_edad/>
   <ciudad>Pamplona</ciudad>
</persona>

ANY:
<!DOCTYPE persona [
   <!ELEMENT persona ANY>
   <!ELEMENT nombre (#PCDATA)>
   <!ELEMENT ciudad (#PCDATA)>
]>

<persona>
   <nombre>Elsa</nombre> vive en <ciudad>Pamplona</ciudad>.
</persona>


-->